templatesDir: path/to/template/directory
openAPIFile: path/to/openapi/file.yaml
outputPath: path/to/output/files/to
template:
  name: test
  moduleName: testModule
  strategy: go
  basePackageName: test
