# render:
#   moduleName: github.com/<account>/<repository>
#   basePackageName: api
#   InvalidRequestStatus: 400
# openapi:
#   openAPIFile: ./docs/openapi.yml
# outputPath: .
# templateDirectory: ./templates
# language: go-gin