openapi: 3.0.0
paths:
  /heartbeat:
    get:
      responses:
        200:
          description: "Serves the API's documentation"
          content:
            "application/json":
              schema: {}
info: {}