openapi: 3.0.0
paths:
  /student:
    get:
      responses:
        200:
          content:
            "application/json":
              schema:
                $ref: "student.yml" # Test refs to entire file
info: {}